# Generated by Django 2.2.4 on 2019-08-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_time', models.DateTimeField(auto_now_add=True)),
                ('box_use', models.CharField(max_length=100)),
                ('size_is_match', models.BooleanField()),
                ('is_packaged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('pick_up_full_name', models.CharField(max_length=150)),
                ('pick_up_address', models.CharField(max_length=150)),
                ('pick_up_city', models.CharField(max_length=100)),
                ('pick_up_state', models.CharField(max_length=100)),
                ('pick_up_zip', models.CharField(max_length=100)),
                ('amazon_QR', models.FileField(blank=True, upload_to='')),
                ('return_label_1', models.FileField(upload_to='')),
                ('return_label_2', models.FileField(blank=True, upload_to='')),
                ('est_item_size', models.CharField(blank=True, max_length=150)),
                ('fragile', models.BooleanField()),
                ('ship_to_full_name', models.CharField(blank=True, max_length=150)),
                ('ship_to_address', models.CharField(blank=True, max_length=150)),
                ('ship_to_city', models.CharField(blank=True, max_length=50)),
                ('ship_to_state', models.CharField(blank=True, max_length=50)),
                ('ship_to_zip', models.CharField(blank=True, max_length=50)),
                ('est_cost', models.DecimalField(decimal_places=3, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_picked_up', models.BooleanField(default=False)),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('shipper_name', models.CharField(max_length=100)),
                ('bag_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Packager')),
                ('Request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Request')),
                ('Shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Shipper')),
            ],
        ),
    ]
