# Generated by Django 2.2.4 on 2019-09-02 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.IntegerField(blank=True, null=True)),
                ('shipper_note', models.CharField(blank=True, help_text='Optional', max_length=300, null=True)),
                ('pickup_time', models.DateTimeField(auto_now=True)),
                ('shipper_name', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_time', models.DateTimeField(auto_now=True)),
                ('size_is_match', models.BooleanField(blank=True, default=True)),
                ('box_use', models.CharField(blank=True, choices=[('1', 'tiny (Evolope)'), ('2', 'small'), ('3', 'medium_side'), ('4', 'medium_normal'), ('5', 'large_normal'), ('6', 'large_gamebox')], help_text='If box size is not match, then what box used', max_length=100)),
                ('packager_note', models.CharField(blank=True, help_text='Optional', max_length=300, null=True)),
                ('tracking_number', models.CharField(blank=True, default='', help_text='They all neeed tracking', max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('packager_name', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_picking_up', models.BooleanField(blank=True, default=False, help_text='Shipper check this box and save BEFORE leaving to pick up')),
                ('is_packaged', models.BooleanField(blank=True, default=False, help_text='Packager check this box when package item')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text="Put in real cost if item size doesn't fit in box", max_digits=10000)),
                ('est_item_size', models.CharField(blank=True, help_text="Put in real size if item size doesn't fit in box", max_length=150)),
                ('pick_up_full_name', models.CharField(max_length=150, null=True)),
                ('pick_up_address', models.CharField(max_length=150, null=True)),
                ('pick_up_city', models.CharField(max_length=100, null=True)),
                ('pick_up_state', models.CharField(max_length=100, null=True)),
                ('pick_up_zip', models.CharField(max_length=100, null=True)),
                ('amazon_QR', models.FileField(blank=True, null=True, upload_to='amazon_QR/%y/%m/%d')),
                ('return_label_1', models.FileField(blank=True, null=True, upload_to='return_label/%y/%m/%d')),
                ('return_label_2', models.FileField(blank=True, null=True, upload_to='return_label/%y/%m/%d')),
                ('fragile', models.BooleanField(blank=True)),
                ('ship_to_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ship_to_address', models.CharField(blank=True, max_length=150, null=True)),
                ('ship_to_city', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_state', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_note', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('verify_code', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('package_info', models.OneToOneField(blank=True, help_text='Packager fill in when package. If none apply, click save anyway', null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Packager')),
                ('pick_up_info', models.OneToOneField(blank=True, help_text='Shipper fill in after pick up', null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Shipper')),
            ],
        ),
    ]
