# Generated by Django 2.2.4 on 2019-08-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amazon_QR',
        ),
        migrations.AddField(
            model_name='request',
            name='amazon_return',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
