# Generated by Django 2.2.4 on 2019-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='pick_up_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='pick_up_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='pick_up_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='pick_up_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='pick_up_zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
