# Generated by Django 2.2.4 on 2019-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0002_auto_20190821_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
