# Generated by Django 2.2.4 on 2019-08-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0002_auto_20190818_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amazon_return',
        ),
        migrations.AddField(
            model_name='request',
            name='amazon_QR',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='fragile',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_label_1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
