# Generated by Django 2.2.4 on 2019-08-28 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Overview', '0002_auto_20190827_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_request',
            name='shipper_name',
        ),
        migrations.AddField(
            model_name='packager',
            name='packager_name',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipper',
            name='shipper_name',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='package_info',
            field=models.ForeignKey(blank=True, help_text='Packager fill in when package. If none apply, click save anyway', null=True, on_delete=django.db.models.deletion.CASCADE, to='Overview.Packager'),
        ),
    ]
