# Generated by Django 2.2.4 on 2019-08-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0003_auto_20190827_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='packager',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='They all neeed tracking', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='packager',
            name='box_use',
            field=models.CharField(blank=True, choices=[('1', 'tiny (Evolope)'), ('2', 'small'), ('3', 'medium_side'), ('4', 'medium_normal'), ('5', 'large_normal'), ('6', 'large_gamebox')], help_text='If box size is not match, then what box used', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='bag_number',
            field=models.IntegerField(),
        ),
    ]
