# Generated by Django 2.2.4 on 2019-08-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0003_auto_20190821_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
