# Generated by Django 2.2.4 on 2019-08-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0004_auto_20190827_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packager',
            old_name='size_not_match',
            new_name='size_is_match',
        ),
    ]
