# Generated by Django 2.2.4 on 2019-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0004_customer_request_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
