# Generated by Django 2.2.4 on 2019-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0005_auto_20190827_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packager',
            name='size_is_match',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
