# Generated by Django 2.2.4 on 2019-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0005_auto_20190821_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='verify_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
