# Generated by Django 2.2.4 on 2019-08-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0006_auto_20190827_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='ship_to_note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
