# Generated by Django 2.2.4 on 2019-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0006_customer_request_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='amazon_QR',
            field=models.FileField(blank=True, null=True, upload_to='amazon_QR/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_1',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_2',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%Y/%m/%D/'),
        ),
    ]
