# Generated by Django 2.2.4 on 2019-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0007_auto_20190823_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='amazon_QR',
            field=models.FileField(blank=True, null=True, upload_to='amazon_QR/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_1',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_2',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%Y/%M/%D/'),
        ),
    ]
