# Generated by Django 2.2.4 on 2019-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0009_auto_20190823_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='amazon_QR',
            field=models.FileField(blank=True, null=True, upload_to='amazon_QR/%request.user%/'),
        ),
    ]
