# Generated by Django 2.2.4 on 2019-08-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0010_auto_20190823_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='amazon_QR',
            field=models.FileField(blank=True, null=True, upload_to='amazon_QR/%request.user/'),
        ),
    ]
