# Generated by Django 2.2.4 on 2019-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0014_auto_20190823_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_1',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='return_label_2',
            field=models.FileField(blank=True, null=True, upload_to='return_label/%y/%m/%d'),
        ),
    ]
